name: config.yml
on:
  push:
    branches:
    - 'master'
    name: deploy
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '14'
      - run: npm install && npm run build 
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: chamara8901
          author_email: chamara@grrow.jp
          message: 'Your commit message'
           run: |
              git checkout gh-pages
              git add .
              git commit -m "Add"
              git pull
              git push origin gh-pages